Repository afkvido/afkvido.github.io, pull requests merged in 2022-02, with the labels that each got.

#12 Add me!
  favicon.png
Labels: Enhancement, Open

#13 remove favicon from jekyll
  index.html
Labels: Bug, Enhancement, Open

#14 idk i think this is old
  69060894.png
Labels: Open

#21 Code of Conduct
  CODE_OF_CONDUCT.md
Labels: Enhancement, Open, Official
